export const CAMPUS_REQUESTS = [
  {
    id: "cr-001",
    name: "Lahore New City Campus",
    category: "Sub",
    city: "Lahore",
    address: "Main Boulevard, Lahore New City, Punjab",
    educationType: "Undergraduate & Graduate",
    submittedBy: "Dr. Asim Raza",
    submittedAt: "2026-08-28T09:14:00Z",
    verificationSource: "hec_auto",
    hecEntry: "HEC Entry #4471",
    status: "pending",
    superAdminStatus: "pending",
    affiliationDoc: "affiliation_proof_lahore_new_city.pdf",
  },
  {
    id: "cr-002",
    name: "Rawalpindi Campus",
    category: "Sub",
    city: "Rawalpindi",
    address: "GT Road, Near Liaquat Bagh, Rawalpindi, Punjab",
    educationType: "Undergraduate",
    submittedBy: "Prof. Mehwish Tariq",
    submittedAt: "2026-08-25T14:30:00Z",
    verificationSource: "manual_proof",
    status: "pending",
    superAdminStatus: "pending",
    affiliationDoc: "affiliation_proof_rawalpindi.pdf",
  },
  {
    id: "cr-003",
    name: "Faisalabad Campus",
    category: "Sub",
    city: "Faisalabad",
    address: "University Town, Faisalabad, Punjab",
    educationType: "Undergraduate & Graduate",
    submittedBy: "Dr. Bilal Ahmed",
    submittedAt: "2026-08-15T11:00:00Z",
    verificationSource: "hec_auto",
    hecEntry: "HEC Entry #3892",
    status: "forwarded",
    superAdminStatus: "auto_approved",
    affiliationDoc: "affiliation_proof_faisalabad.pdf",
  },
];

export const PROGRAM_REQUESTS = [
  {
    id: "pr-001",
    type: "new_offering",
    programName: "BS Artificial Intelligence",
    degreeLevel: "Bachelor",
    discipline: "Computer Science",
    requestingCampus: "Lahore New City Campus",
    requestedBy: "Dr. Nadia Hussain",
    requestedAt: "2026-08-30T10:00:00Z",
    hecRef: "HEC-AI-2024-0145",
    status: "pending",
    systemRecommendation: "auto_approve",
  },
  {
    id: "pr-002",
    type: "new_offering",
    programName: "MS Data Science",
    degreeLevel: "Master",
    discipline: "Data Science",
    requestingCampus: "Rawalpindi Campus",
    requestedBy: "Prof. Usman Ali",
    requestedAt: "2026-08-27T14:00:00Z",
    status: "pending",
    systemRecommendation: "manual_review",
    proofDoc: "program_request_ms_data_science.pdf",
  },
  {
    id: "pr-003",
    type: "new_program",
    programName: "MS Cybersecurity",
    degreeLevel: "Master",
    discipline: "Information Technology",
    requestingCampus: "Main Campus",
    requestedBy: "Dr. Kashif Mehmood",
    requestedAt: "2026-08-20T09:30:00Z",
    hecRef: "HEC-CS-2024-0220",
    justification:
      "Growing demand for cybersecurity professionals in Pakistan's digital transformation era. This program aligns with Pakistan's National Cybersecurity Policy 2021.",
    status: "pending",
    systemRecommendation: "auto_approve",
    proofDoc: "program_request_ms_cybersecurity.pdf",
  },
  {
    id: "pr-004",
    type: "new_program",
    programName: "PhD Quantum Computing",
    degreeLevel: "PhD",
    discipline: "Physics / Computer Science",
    requestingCampus: "Main Campus",
    requestedBy: "Prof. Ayesha Siddiqui",
    requestedAt: "2026-08-18T15:45:00Z",
    justification:
      "Pioneering quantum computing research initiative in collaboration with NUST and PIEAS. No HEC Reference yet — applying for new program approval.",
    status: "pending",
    systemRecommendation: "manual_review",
    proofDoc: "program_request_phd_quantum_computing.pdf",
  },
];

export const PROGRAMS = [
  {
    id: "p-001",
    name: "BS Computer Science",
    degreeLevel: "Bachelor",
    discipline: "Computer Science",
    duration: "4 Years",
    hecRef: "HEC-CS-2010-0012",
    hecDate: "2010-03-15",
    verificationStatus: "verified",
    campuses: ["Main Campus", "Lahore New City Campus", "Faisalabad Campus"],
  },
  {
    id: "p-002",
    name: "MS Computer Science",
    degreeLevel: "Master",
    discipline: "Computer Science",
    duration: "2 Years",
    hecRef: "HEC-CS-2012-0034",
    hecDate: "2012-06-20",
    verificationStatus: "verified",
    campuses: ["Main Campus"],
  },
  {
    id: "p-003",
    name: "PhD Computer Science",
    degreeLevel: "PhD",
    discipline: "Computer Science",
    duration: "3–5 Years",
    hecRef: "HEC-CS-2015-0089",
    hecDate: "2015-09-10",
    verificationStatus: "verified",
    campuses: ["Main Campus"],
  },
  {
    id: "p-004",
    name: "BBA",
    degreeLevel: "Bachelor",
    discipline: "Business Administration",
    duration: "4 Years",
    hecRef: "HEC-BA-2008-0007",
    hecDate: "2008-01-10",
    verificationStatus: "verified",
    campuses: ["Main Campus", "Rawalpindi Campus"],
  },
  {
    id: "p-005",
    name: "MBA",
    degreeLevel: "Master",
    discipline: "Business Administration",
    duration: "2 Years",
    hecRef: "HEC-BA-2009-0018",
    hecDate: "2009-05-22",
    verificationStatus: "verified",
    campuses: ["Main Campus"],
  },
  {
    id: "p-006",
    name: "BS Software Engineering",
    degreeLevel: "Bachelor",
    discipline: "Software Engineering",
    duration: "4 Years",
    hecRef: "HEC-SE-2011-0045",
    hecDate: "2011-08-30",
    verificationStatus: "verified",
    campuses: ["Main Campus", "Faisalabad Campus"],
  },
  {
    id: "p-007",
    name: "MS Data Science",
    degreeLevel: "Master",
    discipline: "Data Science",
    duration: "2 Years",
    hecRef: "HEC-DS-2022-0178",
    hecDate: "2022-04-15",
    verificationStatus: "pending",
    campuses: [],
  },
  {
    id: "p-008",
    name: "BS Electrical Engineering",
    degreeLevel: "Bachelor",
    discipline: "Electrical Engineering",
    duration: "4 Years",
    hecRef: "HEC-EE-2005-0003",
    hecDate: "2005-03-01",
    verificationStatus: "verified",
    campuses: ["Main Campus"],
  },
  {
    id: "p-009",
    name: "LLB",
    degreeLevel: "Bachelor",
    discipline: "Law",
    duration: "3 Years",
    hecRef: "HEC-LW-2007-0009",
    hecDate: "2007-11-12",
    verificationStatus: "verified",
    campuses: ["Main Campus"],
  },
  {
    id: "p-010",
    name: "BS Mathematics",
    degreeLevel: "Bachelor",
    discipline: "Mathematics",
    duration: "4 Years",
    hecRef: "HEC-MA-2006-0005",
    hecDate: "2006-07-20",
    verificationStatus: "verified",
    campuses: ["Main Campus", "Lahore New City Campus"],
  },
];

export const ACTIVITY_LOG = [
  {
    id: "al-001",
    timestamp: "2026-09-04T08:30:00Z",
    actor: "System (HEC Auto-Match)",
    actorType: "system",
    action: "auto_approved",
    entityType: "campus",
    entityName: "Faisalabad Campus",
    reason:
      "Auto-approved because campus matched HEC entry #3892 for University of the Punjab with 100% name and district match.",
  },
  {
    id: "al-002",
    timestamp: "2026-09-03T14:15:00Z",
    actor: "Admin: Muhammad Hassan",
    actorType: "human",
    action: "forwarded",
    entityType: "campus",
    entityName: "Rawalpindi Campus",
    reason:
      "Forwarded to Super Admin after Tier-1 approval — campus requires manual HEC verification as no automated entry found.",
  },
  {
    id: "al-003",
    timestamp: "2026-09-02T11:00:00Z",
    actor: "System (Domain Verifier)",
    actorType: "system",
    action: "verified",
    entityType: "university",
    entityName: "University of the Punjab",
    reason:
      "Domain verification completed via one-time link click on registrar@uop.edu.pk. University status upgraded to Verified.",
  },
  {
    id: "al-004",
    timestamp: "2026-09-01T09:45:00Z",
    actor: "System (HEC Auto-Match)",
    actorType: "system",
    action: "auto_approved",
    entityType: "program",
    entityName: "BS Artificial Intelligence",
    reason:
      "Auto-approve eligible — HEC Reference HEC-AI-2024-0145 verified against HEC master program list. Forwarded to Super Admin for one-click approval.",
  },
  {
    id: "al-005",
    timestamp: "2026-08-30T16:20:00Z",
    actor: "Admin: Muhammad Hassan",
    actorType: "human",
    action: "rejected",
    entityType: "program",
    entityName: "MS Quantum Finance",
    reason:
      "Rejected at Tier-1 — no HEC Reference provided and no matching entry in HEC master program list. Admin requested resubmission with valid HEC documentation.",
  },
  {
    id: "al-006",
    timestamp: "2026-08-28T10:30:00Z",
    actor: "Admin: Muhammad Hassan",
    actorType: "human",
    action: "forwarded",
    entityType: "program",
    entityName: "MS Data Science",
    reason:
      "Forwarded to Super Admin — campus (Rawalpindi) not yet HEC-verified. Manual review required before approval.",
  },
  {
    id: "al-007",
    timestamp: "2026-08-25T14:00:00Z",
    actor: "System (HEC Auto-Match)",
    actorType: "system",
    action: "auto_approved",
    entityType: "campus",
    entityName: "Lahore New City Campus",
    reason:
      "Auto-approved because campus matched HEC entry #4471 with confirmed affiliation to University of the Punjab.",
  },
  {
    id: "al-008",
    timestamp: "2026-08-20T08:00:00Z",
    actor: "Super Admin: Fatima Zahra",
    actorType: "human",
    action: "revision_requested",
    entityType: "program",
    entityName: "PhD Quantum Computing",
    reason:
      "Super Admin requested revision — additional supporting documentation required including faculty CVs and lab infrastructure proof.",
  },
  {
    id: "al-009",
    timestamp: "2026-08-15T13:20:00Z",
    actor: "Admin: Muhammad Hassan",
    actorType: "human",
    action: "submitted",
    entityType: "program",
    entityName: "MS Cybersecurity",
    reason:
      "New program request submitted with HEC Reference HEC-CS-2024-0220. Pending Tier-1 review.",
  },
  {
    id: "al-010",
    timestamp: "2026-08-10T09:00:00Z",
    actor: "System (HEC Auto-Match)",
    actorType: "system",
    action: "auto_approved",
    entityType: "program",
    entityName: "BS Computer Science",
    reason:
      "Auto-approved and marked verified — HEC Reference HEC-CS-2010-0012 confirmed active and accredited.",
  },
];
